[workspace]
members = ["packages/*"]

[profile.profiling]
unstable-add-statements-functions-debug-info = true
unstable-add-statements-code-locations-debug-info = true

[profile.proving]
inherits = "release"

[profile.proving.cairo]
enable-gas = false