[package]
name = "starkstr"
version = "0.1.0"
edition = "2024_07"

[dependencies]
alexandria_math = { git = "https://github.com/keep-starknet-strange/alexandria.git" }


[dev-dependencies]
cairo_test = "2.9.2"
