[package]
name = "aggsig_checker"
version = "0.1.0"
edition = "2024_07"

[dependencies]
garaga = { git = "https://github.com/m-kus/garaga", rev = "65db99b8ba9ff19e7f19609cd06f8220d8406881" }
cairo_execute = "2.9.2"

[executable]

[lib]

[dev-dependencies]
cairo_test = "2.9.2"
