name: AggSig Checker Cairo

on:
  push:
    branches: [ main ]
  pull_request:

permissions: read-all

jobs:
  fmt:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Scarb
        uses: software-mansion/setup-scarb@v1
        with:
          scarb-version: "nightly"

      - name: Check cairo format
        run: scarb fmt --check
        working-directory: packages/aggsig_checker

  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Setup Rust
        uses: dtolnay/rust-toolchain@stable

      - name: Install Scarb
        run: |
          cd packages/aggsig_checker
          make install-scarb

      - name: Build cairo onchain
        run: scarb build
        working-directory: packages/aggsig_checker

  test:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@main

      - name: Set up Scarb
        uses: software-mansion/setup-scarb@v1
        with:
          scarb-version: "nightly"

      - name: Run tests and generate report
        run: scarb test
        working-directory: packages/aggsig_checker
