name: End-to-End Testing

on:
  push:
    branches: [ main ]
  pull_request:

permissions: read-all

jobs:
  e2e:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Install Rust nightly
        uses: dtolnay/rust-toolchain@nightly

      - name: Install Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.10'

      - name: Install Scarb
        uses: software-mansion/setup-scarb@v1
        with:
          scarb-version: "nightly"

      - name: Install Stwo and Python dependencies
        run: |
          rustup default nightly
          cd packages/aggsig_checker
          make install

      - name: Run end-to-end test
        run: |
          cd packages/aggsig_checker
          make build
          make execute
          make prove
