name: End-to-End Testing

on:
  push:
    branches: [ main ]
  pull_request:

permissions: read-all

jobs:
  e2e:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: "18"
          cache: "npm"
          cache-dependency-path: apps/aggsig_checker_cli/package-lock.json

      - name: Setup Rust nightly
        uses: dtolnay/rust-toolchain@nightly

      - uses: actions/setup-python@v5
        with:
          python-version: '3.10'

      - name: Install Scarb
        uses: software-mansion/setup-scarb@v1
        with:
          scarb-version: "2.10.0-rc.1"

      - name: Install Stwo and other dependencies
        run: |
          rustup default nightly
          cd packages/aggsig_checker
          make install

      - name: Run end-to-end test
        run: |
          cd packages/aggsig_checker
          make e2e
