name: End-to-End Testing

on:
  push:
    branches: [ main ]
  pull_request:

permissions: read-all

jobs:
  e2e:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: "18"
          cache: "npm"
          cache-dependency-path: apps/aggsig_checker_cli/package-lock.json

      - name: Setup Rust stable
        uses: dtolnay/rust-toolchain@stable

      - name: Setup Rust nightly
        uses: dtolnay/rust-toolchain@nightly

      - name: Install Scarb
        run: |
          rustup default stable
          cd packages/aggsig_checker
          make install-scarb

      - name: Install Stwo
        run: |
          rustup default nightly
          cd packages/aggsig_checker
          make install-stwo

      - name: Install jq
        run: sudo apt-get install -y jq

      - name: Install CLI dependencies
        run: |
          cd apps/aggsig_checker_cli
          npm i
          cd ../..

      - name: Run end-to-end test
        run: |
          chmod +x scripts/verify_nostr_event_batch_signatures.sh
          ./scripts/verify_nostr_event_batch_signatures.sh
